name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ffmpeg (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install ffmpeg -y

      - name: Install ffmpeg (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install ffmpeg -y

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --paths . --name Youtube_conversor main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Youtube_conversor-${{ matrix.os }}
          path: dist/